#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoomiesCalc.Droid.Resource", IsApplication=true)]

namespace RoomiesCalc.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030002
			public const int RC_Green = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int RC_Pink = 2130903041;
			
			// aapt resource value: 0x7f030005
			public const int blueDark = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int blueLight = 2130903046;
			
			// aapt resource value: 0x7f030004
			public const int bluePrimary = 2130903044;
			
			// aapt resource value: 0x7f030009
			public const int grayDark = 2130903049;
			
			// aapt resource value: 0x7f030008
			public const int grayLight = 2130903048;
			
			// aapt resource value: 0x7f03000a
			public const int grayMedium = 2130903050;
			
			// aapt resource value: 0x7f030007
			public const int grayPrimary = 2130903047;
			
			// aapt resource value: 0x7f030003
			public const int greenDark = 2130903043;
			
			// aapt resource value: 0x7f03000b
			public const int purpleDark = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int purplePrimary = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int textPrimary = 2130903053;
			
			// aapt resource value: 0x7f030000
			public const int white = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bg1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bg2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Cross = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Group = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Notification = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int RCEntry = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Share = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
